Implemented typography component
daboigbae/react-native-component-lib pull request #18
Opened 2022-10-06 02:32 UTC by Manbeartrain

![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 20 31 51](https://user-images.githubusercontent.com/30089055/194201139-cc79a510-583a-4f68-b3d2-cd21bab6422e.png)
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 20 32 04](https://user-images.githubusercontent.com/30089055/194201145-e70f42e5-4908-4006-ac4c-3d04d4ddce61.png)
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 20 32 11](https://user-images.githubusercontent.com/30089055/194201146-7dcd33a6-f4cc-4f9d-a232-883d83305755.png)

2022-10-06 12:23 UTC, daboigbae requested changes

2022-10-06 12:23 UTC, daboigbae commented on src/components/Typography/Typography.tsx
> +const Typography: React.FC<TextType> = ({ text, textColor, type }) => {
Let's make this Text instead of typography

2022-10-06 12:23 UTC, daboigbae commented on src/components/Typography/Typography.tsx
> +import { StyleSheet, Text } from "react-native";
you can import this text using

Text as RnText 


That way whenever we see text, we know that we have to replace with one of ours

2022-10-06 12:23 UTC, daboigbae commented on src/components/Typography/Typography.tsx
> +		type: true
should type be true here? it's a string from the typescript right? So maybe it doesn't need to be here

2022-10-06 20:43 UTC, Manbeartrain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feature/text](https://trello.com/c/Ib6Qxlj0/16-feature-text)

2022-10-07 00:54 UTC, daboigbae approved these changes

2022-10-07 00:54 UTC, merged