Implemented Card Component
daboigbae/react-native-component-lib pull request #19
Opened 2022-10-06 20:42 UTC by Manbeartrain

https://user-images.githubusercontent.com/30089055/194414592-f39d8003-97a5-4b5b-bc43-8d09ca65c551.mp4

2022-10-06 20:43 UTC, Manbeartrain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feature/card-component](https://trello.com/c/eB5dNvrb/3-feature-card-component)

2022-10-07 18:03 UTC, daboigbae requested changes

2022-10-07 18:03 UTC, daboigbae commented on src/components/Card/Card.tsx
> +	containedCard: {},
this looks unused

2022-10-07 18:03 UTC, daboigbae commented on src/components/Card/Card.tsx
> +	const generatedStyle = generateCardBaseStyle(cardColor?.[0], type);
look at how I did the style for the text, let's use composition instead of using spread ooperator to merge styles

2022-10-07 21:40 UTC, daboigbae approved these changes

2022-10-07 21:41 UTC, merged